"""Legacy AxisDriver Modbus constants."""

from __future__ import annotations

MOTION_STATE_REGISTER = 101
MOTION_DIRECTION_REGISTER = 102
RAW_POSITION_REGISTER = 103
ENDSTOP_REGISTER = 104
RELEASE_REGISTER = 105
INDEX_REGISTER = 106
MOTOR_ALARM_REGISTER = 107

COMMAND_REGISTER = 201
SPEED_REGISTER = 202
ENDSTOP_ENABLE_REGISTER = 203
COMMAND_TRIGGER_REGISTER = 301
PARAMETER_TRIGGER_REGISTER = 302
OFFSET_REGISTER = 303

MOTION_STOP = 10
MOTION_CW = 100
MOTION_CCW = 101

MODBUS_NOT_CONNECTED = 0
MODBUS_OK = 1
MODBUS_FAIL = 2


def format_release(value: int | None) -> str | None:
    if value is None:
        return None
    return f"{float(value) / 100.0:.2f}"
